controllers:
    resource: ../src/Controller/
    type: annotation
#    resource: "@App/Controller/LogBookSecurityController"
#    type:     annotation
#    prefix:   /login
#    schemes:  ['%httpProtocol%']