index:
    path: /
    controller: App\Controller\LogBookDefaultController::index

login:
    controller: App\Controller\LogBookSecurityController::login
    path:   /login

register:
    controller: App\Controller\LogBookRegistrationController::register
    path:   /register